set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports lap_reset_raw]
set_property IOSTANDARD LVCMOS33 [get_ports pause_start_raw]


set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property PACKAGE_PIN W19 [get_ports lap_reset_raw]
set_property PACKAGE_PIN T17 [get_ports pause_start_raw]


set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property PACKAGE_PIN W4 [get_ports {SSD[3]}]
set_property PACKAGE_PIN V4 [get_ports {SSD[2]}]
set_property PACKAGE_PIN U4 [get_ports {SSD[1]}]
set_property PACKAGE_PIN U2 [get_ports {SSD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pattern[0]}]
set_property PACKAGE_PIN W7 [get_ports {pattern[7]}]
set_property PACKAGE_PIN W6 [get_ports {pattern[6]}]
set_property PACKAGE_PIN U8 [get_ports {pattern[5]}]
set_property PACKAGE_PIN V8 [get_ports {pattern[4]}]
set_property PACKAGE_PIN U5 [get_ports {pattern[3]}]
set_property PACKAGE_PIN V5 [get_ports {pattern[2]}]
set_property PACKAGE_PIN U7 [get_ports {pattern[1]}]
set_property PACKAGE_PIN V7 [get_ports {pattern[0]}]
